Added Tailwind, big refactor
hawaiians/hawaiiansintech pull request #17
Opened 2023-06-29 02:51 UTC by taylorkmho

<img width="480" alt="image" src="https://github.com/hawaiiansintech/hawaiiansintech/assets/5141111/28100891-6c1e-4911-b489-598d66b56cf2">

- **Added Tailwind**: I added the recommended tailwind vscode extension, which adds intellisense. Adding the `prettier-plugin-tailwindcss` Prettier package automatically turns it on.

- **New homepage**: Visual design and interaction pass on the homepage. Playing around with using a separate, contrast-y visual for the global selected pills.

- **Refactored all the things:** Refactored _a lot_ of our UI to use tailwind class names. Their docs are actually super useful (I started using cmd + k really good by the end of this 😆

- **Well, nearly all the things:** Chose to delete unused code instead of refactor, including BannerAlert, etc. The goal is to eventually migrate some components into the [shadcn/ui](https://ui.shadc.com/docs/) library.

### Test case:
- Open [homepage](https://hawaiiansintech-4t97w7cvd-hawaiians.vercel.app/) and play with filtering.
- Go through Join and Request Changes flow.
- Read About page.
- ~Thank you and Hackathon pages still needs refactor~

2023-07-01 01:30 UTC, eparubrub requested changes
Looked over everything, most if not all changes are UI specific and not changing any functional/data stuff. I really like the updates, cleans up a lot of the <style jsx> tags that we have

I tested out the join workflows and everything seemed to be in order and reflecting on the backside. The only real issue I found was the `fda` text I mentioned below, and the UI on the iphone seems to be a bit laggy/jittery, but that might be because of the vercel hosting, will send my screen cap on discord. But I think after that `fda` fix we're good.

Also, thanks for the updates, I can't imagine how much time you put into this refactor

2023-07-01 01:30 UTC, eparubrub commented on pages/index.tsx
> -  const [viewAll, setViewAll] = useState<Boolean>(true);
oh woops hope that wasn't me, just read about the difference between these - https://stackoverflow.com/a/64443353

2023-07-01 01:30 UTC, eparubrub commented on pages/join/03-company.tsx
> +                    setIndustrySuggested(e.target.value + "fda");
errrr is this `fda` thing supposed to be here? it's adding this unexpected text when I'm typing "test"

![Jun-30-2023 18-02-50](https://github.com/hawaiians/hawaiiansintech/assets/26368729/f1a0c47c-d6ed-440e-b39e-81c401b16343)

2023-07-04 02:21 UTC, taylorkmho commented on pages/index.tsx
> -  const [viewAll, setViewAll] = useState<Boolean>(true);
All good. Got me to look for others, found a couple more. Fixed in a commit.

2023-07-04 03:22 UTC, eparubrub approved these changes

2023-07-04 03:29 UTC, taylorkmho commented
- [x] **Fixed `fda` bug.** Prob was testing something and forgot.
- [x] **Removed `MemberDirectory` animation altogether.** It was starting to bug once I converted it to the grid layout (versus the old table rows).
- [x] **Replaced all `Boolean` → `boolean`.**

2023-07-06 04:03 UTC, merged